name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: Set up Node.js
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version-file: package.json
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Check code formatting
        run: npm run fmt:check

      - name: Lint code
        run: npm run lint

      - name: Run typecheck
        run: npm run typecheck

  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: Set up Node.js
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version-file: package.json
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Run tests
        run: npm run test

      # Dogfooding the app with the Vitest HTML reporter
      - name: Upload test HTML report
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: always()
        with:
          name: vitest-html-report
          path: |
            .vitest/
          retention-days: 1
          include-hidden-files: true

      - name: Upload test results to codecov
        uses: codecov/codecov-action@303a32d7a59b442fa8d48b6a1cc6825c09c847a5 # v7.1.1
        with:
          use_oidc: true
          fail_ci_if_error: false
          report_type: test_results
          files: junit.xml
          flags: unit

      - name: Upload coverage report
        uses: codecov/codecov-action@303a32d7a59b442fa8d48b6a1cc6825c09c847a5 # v7.1.1
        with:
          use_oidc: true
          fail_ci_if_error: false
          files: coverage/clover.xml
          flags: unit
